sudo: required

language: go

services:
  - docker

go:
  - "1.10"

before_script:
  - go get -t
  - sudo service mysql stop
  - docker-compose up -d
  - wget -q -O ./waitforit https://github.com/maxcnunes/waitforit/releases/download/v2.4.0/waitforit-linux_amd64
  - chmod +x ./waitforit
  - source test.env
  - ./waitforit -address tcp://$TRAFFIC_INPUT_HOST:$TRAFFIC_INPUT_PORT -timeout 30 || travis_terminate 1;
  - source test.env && ./waitformysql.sh

script:
  - go test -v -race || travis_terminate 1;

  - go build -ldflags "-s -w" -o build/package/traffic cmd/traffic/traffic.go || travis_terminate 1;
  - docker build build/package/ -t $DOCKER_REPO || travis_terminate 1;

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $DOCKER_REPO;
    fi

  