sudo: required

dist: focal

language: go

go:
  - "1.15"

services:
  - rabbitmq
  - postgresql

addons:
  apt:
    packages:
      - rabbitmq-server
  postgresql: "13"
  sonarcloud:
    organization: "autowp-github"
    token:
      secure: $SONARCLOUD_TOKEN

install: true

before_script:
  - go mod verify || travis_terminate 1;
  - go get -u github.com/kisielk/errcheck || travis_terminate 1;
  - go get -u github.com/mattn/goveralls || travis_terminate 1;
  - errcheck ./... || travis_terminate 1;
  - wget -q -O ./waitforit https://github.com/maxcnunes/waitforit/releases/download/v2.4.1/waitforit-linux_amd64 || travis_terminate 1;
  - chmod +x ./waitforit
  - ./waitforit -address tcp://127.0.0.1:5432 -timeout 30 || travis_terminate 1;
  - ./waitforit -address tcp://127.0.0.1:5672 -timeout 30 || travis_terminate 1;
  - psql -c 'CREATE DATABASE traffic;' -U postgres
  - psql -c "CREATE USER traffic WITH PASSWORD 'password';" -U postgres
  - psql -c 'GRANT ALL PRIVILEGES ON DATABASE traffic TO traffic;' -U postgres
  - psql -c 'GRANT ALL PRIVILEGES ON SCHEMA public TO traffic;' -U postgres traffic

script:
  - go test -v -race -coverprofile=cov.out || travis_terminate 1;
  - sonar-scanner -Dsonar.login=$SONARCLOUD_TOKEN || true;
  - goveralls -service=travis-ci || travis_terminate 1;

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker build . -t autowp/traffic || travis_terminate 1;
    docker push autowp/traffic;
    fi
