sudo: required

language: go

go:
  - "1.14"

services:
  - rabbitmq

addons:
  postgresql: "13"
  apt:
    packages:
    - postgresql-13
    - postgresql-client-13
    - rabbitmq-server
  sonarcloud:
    organization: "autowp-github"
    token:
      secure: $SONARCLOUD_TOKEN

install: true

before_script:
  - go mod verify
  - go get -u github.com/kisielk/errcheck
  - go get -u github.com/mattn/goveralls
  - errcheck ./...
  - wget -q -O ./waitforit https://github.com/maxcnunes/waitforit/releases/download/v2.4.1/waitforit-linux_amd64
  - chmod +x ./waitforit
  - source test.env
  - ./waitforit -address tcp://$TRAFFIC_RABBITMQ_HOST:$TRAFFIC_RABBITMQ_PORT -timeout 30 || travis_terminate 1;

script:
  - go test -v -race -coverprofile=cov.out || travis_terminate 1;
  - sonar-scanner -Dsonar.login=$SONARCLOUD_TOKEN || true;
  - goveralls -service=travis-ci || travis_terminate 1;

  - go build -ldflags "-s -w" -o build/package/traffic cmd/traffic/traffic.go || travis_terminate 1;
  - cp -R migrations build/package/migrations
  - docker build build/package/ -t $DOCKER_REPO || travis_terminate 1;

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $DOCKER_REPO;
    fi
