---
input:
  address: amqp://guest:guest@localhost:5672/
  queue: input
rollbar:
  token: 
  environment: development
  period: 1m
dsn: root:password@tcp(localhost)/traffic?charset=utf8mb4&parseTime=true&loc=UTC
