version: '2'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
    - "5672:5672"
    - "15672:15672"

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
    - POSTGRES_DB=traffic
    - POSTGRES_USER=traffic
    - POSTGRES_PASSWORD=password
    ports:
    - "5432:5432"

